# Generated by Django 2.2.2 on 2019-06-22 20:44

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('podpiska_do', models.DateField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=120, null=True)),
                ('set_webhook', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('off', 'НЕ подключен'), ('on', 'Подключен')], default='init', max_length=120, null=True)),
                ('last_log_set_webhook', models.CharField(blank=True, max_length=255, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('date_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Бот',
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('step', models.CharField(blank=True, max_length=255, null=True)),
                ('date_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.Bot')),
            ],
            options={
                'verbose_name': 'TelegramBot User',
                'verbose_name_plural': 'TelegramBot User',
                'unique_together': {('bot', 'chat_id')},
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_or_out', models.CharField(blank=True, choices=[('in', 'Вебхуки'), ('out', 'Отправленные сообщения')], max_length=120, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('answer_out_mes_request', models.TextField(blank=True, null=True)),
                ('date_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.Bot')),
                ('bot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.BotUser')),
            ],
            options={
                'verbose_name': 'Логи',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='Compaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(blank=True, choices=[('created', 'Создана'), ('in_progress', 'Выполняется'), ('success', 'Успешно'), ('error', 'Ошибка')], max_length=120, null=True)),
                ('date_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.Bot')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылка',
            },
        ),
    ]
