# Generated by Django 2.2.2 on 2019-06-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='status',
            field=models.CharField(blank=True, choices=[('off', 'НЕ подключен'), ('on', 'Подключен')], default='off', max_length=120, null=True),
        ),
    ]
