# Generated by Django 2.2.2 on 2019-06-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_auto_20190628_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='last_log_set_webhook',
            field=models.TextField(blank=True, null=True),
        ),
    ]
