# Generated by Django 2.2.2 on 2019-07-02 15:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0007_auto_20190702_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
    ]
