# Generated by Django 2.2.2 on 2019-07-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0009_auto_20190721_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='podpiska_do',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
