# Generated by Django 2.2.2 on 2019-07-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0010_auto_20190721_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaign',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'Создана'), ('in_progress', 'Выполняется'), ('success', 'Успешно'), ('error', 'Ошибка')], default='created', max_length=120, null=True),
        ),
    ]
