# Generated by Django 2.2.2 on 2019-07-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0012_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
