# Generated by Django 2.2.2 on 2019-07-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0014_payment_subscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
