# Generated by Django 2.2.2 on 2019-07-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0016_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=255, unique=True)),
                ('date_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.Bot')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='subscription_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.BigIntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cabinet.Subscription'),
            preserve_default=False,
        ),
    ]
